# Utiliser l'image officielle de phpMyAdmin
FROM phpmyadmin/phpmyadmin:latest

# Définir les variables d'environnement pour connecter phpMyAdmin à MariaDB
ENV PMA_HOST=mariadb
ENV MYSQL_ROOT_PASSWORD=emile

# Exposer le port 80 pour accéder à phpMyAdmin
EXPOSE 80
