# Utiliser l'image officielle de MariaDB
FROM mariadb:latest

# Définir les variables d'environnement pour la base de données
ENV MYSQL_ROOT_PASSWORD=emile
ENV MYSQL_DATABASE=db_nodered
ENV MYSQL_USER=ec
ENV MYSQL_PASSWORD=ec

# Exposer le port 3306
EXPOSE 3306
